### ISSUE TITLE
[BUG] http://geo.loop-gis.org/models/vtkleaflet_2021-03-19-11-40.html

### ISSUE THREAD

**Issue by RichardScottOZ** [Loop3D/map2loop-2#103]
### Describe your issue

Just tried the example model link, no luck, is it working ok for you?

I have just pointed out Loop to some colleagues.

### Minimal reproducing code example

```python
Link in browser [chrome].
```

**Comment by markjessell** [comment]
link fixed...

**Comment by RichardScottOZ** [comment]
That seems good!
