### ISSUE TITLE
[BUG] field renaming issues

### ISSUE THREAD

**Issue by markjessell** [Loop3D/map2loop-2#106]
### Describe your issue

A couple of errors arising now that field names are reset in map2loop

1) map2loop fails if I use the same column for "min" and "max" in the json dictionary. Often I hard define the stratigraphic order for maps because they are not provided by the original map. Creating a single column of ages then makes sense, but now fails becasue the column name is changed to MIN_AGE for the first case and therefore is no longer available for the seond usage.

2) Similarly map2loop fails if one of the original columns was called CODE as this will cause a clash when the column that is defined by "c" in the json file attempts to be renamed. This will happen if ANY of the previous field names happen to coincide with those defined in the json file.

### Minimal reproducing code example

```python
1) set min and max to the same field

2) set any field name to a pre-defined internal name
```

### Error message

```shell
1)   File "/home/mark/map2loop-2_latest/map2loop-2/map2loop/mapdata.py", line 317, in check_map
    raise NameError(
NameError: ERROR: data does not contain column SO_ORDER

2)   File "/home/mark/map2loop-2_latest/map2loop-2/map2loop/mapdata.py", line 470, in export_wkt_format_files
    sub_geol = geology[columns]
  File "/home/mark/anaconda3/envs/m2l2-py39/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1415, in __getitem__
    result = super().__getitem__(key)
  File "/home/mark/anaconda3/envs/m2l2-py39/lib/python3.9/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/mark/anaconda3/envs/m2l2-py39/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/mark/anaconda3/envs/m2l2-py39/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['CODE'] not in index"
```

**Comment by RoyThomsonMonash** [comment]
Hi Mark,

I've added a check for when the min and max age fields are set to the same column and separated them.  I also added a check for when internal reserved column names are used which will raise an exception with a comment to rename those columns (this is a bit cumbersome but it is the best option for the moment).  The master branch and the next release will have these fixed.

**Comment by markjessell** [comment]
Thanks that sounds great

m
