### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ice-jing** [Loop3D/map2loop-2#112]
Example 2 - Draw Your Own Area——Error
proj.update_config()

--> 447 self.map_data.load_all_map_data(self.config)
NameError: map2loop error: Could not access DTM server after 10 attempts
What can I do about this error?

**Comment by ice-jing** [comment]
@markjessell  Can you help me？

**Comment by markjessell** [comment]
Hi this call failed because the code could not access the Geoscience Australia DTM sever. I just tried it this morning and the server was working for me. Their server does sometimes go down so it may be worth trying again.

The second issue is that because it is performing a remote access to their server you do need to have an internet connection when you run this code so maybe check for firewall restrictions?

Cheers
Mark

Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E ***@***.***

________________________________

**Comment by ice-jing** [comment]
AttributeError: 'Config' object has no attribute 'c_l'
@markjessell

**Comment by markjessell** [comment]
This looks like a problem with the path to the json file or a problem with that file itself, hard to tell without more information.

Cheers

mark

**Comment by ice-jing** [comment]
` proj.update_config(
      2                     out_dir=model_name,
      3                     bbox_3d={
      4                          "minx": 515687.31005864, # region of interest for GMD paper
      5                          "miny": 7473446.76593407,
      6                          "maxx": 562666.860106543,
      7                          "maxy": 7521273.57407786,
      8                          "base": -3200,
      9                          "top": 1200,
     10                      },
     11                     run_flags={                        
     12                         'aus': True,
     13                         'close_dip': -999,
     14                         'contact_decimate': 5,
     15                         'contact_dip': -999,
     16                         'contact_orientation_decimate': 5,
     17                         'deposits': "Fe,Cu,Au,NONE",
     18                         'dist_buffer': 10,
     19                         'dtb': '',
     20                         'fat_step': 750,
     21                         'fault_decimate': 5,
     22                         'fault_dip': 90,
     23                         'fold_decimate': 5,
     24                         'interpolation_scheme': 'scipy_rbf',
     25                         'interpolation_spacing': 500,
     26                         'intrusion_mode': 0,
     27                         'max_thickness_allowed': 10000,
     28                         'min_fault_length': 5000,
     29                         'misorientation': 30,
     30                         'null_scheme': 'null',
     31                         'orientation_decimate': 0,
     32                         'pluton_dip': 45,
     33                         'pluton_form': 'saucers',
     34                         'thickness_buffer': 5000,
     35                         'use_fat': False,
     36                         'use_interpolations': False,
     37                         'fault_orientation_clusters':2,
     38                         'fault_length_clusters':2
     39                     },
     40                   )`
When executing the above code, there is always an error. 
NameError: map2loop error: Could not access DTM server after 10 attempts

**Comment by markjessell** [comment]
Maybe try this test code to see if you are getting access directly?

Cheers

Mark




from owslib.wcs import WebCoverageService

url = http://services.ga.gov.au/gis/services/DEM_SRTM_1Second_over_Bathymetry_Topography/MapServer/WCSServer?
bbox=(520000, 550000,7490000,7510000)

wcs = WebCoverageService(url, version="1.0.0")
cvg = wcs.getCoverage(identifier="1", bbox=bbox, format="GeoTIFF", crs=4326, width=200, height=200)

path_out='test.tif'
f = open('path_out', "wb")
f.write(cvg.read())
f.close()

print("dtm geotif saved as", path_out)

**Comment by ice-jing** [comment]
@markjessell I can only open the link below, but not the one above.
https://services.ga.gov.au/site_9/services/DEM_SRTM_1Second_over_Bathymetry_Topography/MapServer/WCSServer?request=GetCapabilities&service=WCS

**Comment by markjessell** [comment]
Do you get an error message?

**Comment by ice-jing** [comment]
When I open the URL, it gives the following error.
http://13.211.217.129:8080/geoserver/loop/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=loop:500k_geol_28350&bbox={BBOX_STR}&srs=EPSG:28350&outputFormat=shape-zip
HTTP Status 400 – Bad Request  Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986.
But,I can open the following URL
http://13.211.217.129:8080/geoserver/loop/wms?service=WMS&version=1.1.0&request=GetMap&layers=loop%3A500k_geol_28350&bbox=90196.4296875%2C6106193.5%2C1799130.25%2C8464417.0&width=556&height=768&srs=EPSG%3A28350&styles=&format=application/openlayers#

**Comment by lachlangrose** [comment]
In the first url it looks like you have not replaced the {BBOX_STR} with
bounding box coordinates?

**Comment by ice-jing** [comment]
ok,the modification successfully downloaded the data, but when I run the following code, I get an error
proj.update_config(
                    out_dir=model_name,
                    bbox_3d={
                         "minx": 515687.31005864, # region of interest for GMD paper
                         "miny": 7473446.76593407,
                         "maxx": 562666.860106543,
                         "maxy": 7521273.57407786,
                         "base": -3200,
                         "top": 1200,
}
ValueError: zero-size array to reduction operation maximum which has no identity
@markjessell

**Comment by markjessell** [comment]
Can you provide the whole code that you are trying to run please.

mark

**Comment by ice-jing** [comment]
https://github.com/Loop3D/map2loop2-notebooks/blob/master/Example%201%20-%20Using%20Loop's%20Sources.ipynb
It's Example 1 from the map2loop notebook.

**Comment by ice-jing** [comment]
Example 3 - Local Source Data can be run and successfully outputs data. @markjessell

**Comment by ice-jing** [comment]
Why is the output file from map2loop not complete, e.g. part of the stratum is missing from ASUD_strat.gml. What is the problem please? @markjessell @lachlangrose

**Comment by markjessell** [comment]
Hi I have been in touch with GA and thier DTM server is indeed down at the moment. For future reference, if there is an issue with the DTM server you can email eGIS@ga.gov.au with a request to retart it and they are very helpful, although it may take a day or two this time as there is a proxy issue to deal with.

**Comment by markjessell** [comment]
GA has now fixed thier DTM server and for me at least the download is now working again.

For future reference, if this happens again and I don't notice it, you can contact eGIS <eGIS@ga.gov.au> 

and they will fix it.
