### ISSUE TITLE
Overwriting the output dir is unpredictable

### ISSUE THREAD

**Issue by yohanderose** [Loop3D/map2loop-2#31]
* On some computers shutil.rmtree takes longer than the sleep time allocated
* It might be useful to have an 'inplace' option which would allow users to have map2loop output files open in other software while rerunning map2loop

**Comment by lachlangrose** [comment]
Could you only export files when required and store the rest inside a loop
project file?

**Comment by yohanderose** [comment]
Solved by commit b6b6d19664ef4d2bd4f3e1d30460f0708e27c3d1. Overwrite flag now accepts a string 'true' for a complete remove, 'false' the default presumed user error and 'in-place' if you don't wish to create a new output file structure but don't mind things overwriting. Complete removal now waits for the existing output directory to be erased before re-creating.
