### ISSUE TITLE
warnings when incorrect parameters are given

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop-2#50]
```
import os
import hjson
from map2loop.project import Project
proj = Project( 
                 loopdata_state = "WA",)
)                

proj.update_config(
                    out_dir='./gmdpaper-faultslip',
                    bbox_3d=bbox_3d,
                    proj_crs={'init': 'EPSG:28350'},
                    overwrite='true',
                  )
```

If overwrite is set to a boolean type, True it does not work. It should at least tell the user its the wrong type, considering the logical type for this parameter is a boolean

**Comment by yohanderose** [comment]
Users can now pass a bool to overwrite, printing a warning. If true, we convert to the string 'true'. If False, we warn and call the typical overwrite catch which is now a function c71cadf02bc761c95017f56897aff76448ea53ca
