### ISSUE TITLE
Add ability to configure map_checker

### ISSUE THREAD

**Issue by markjessell** [Loop3D/map2loop-2#56]
Can we have the ability to control behaviour of map_checker (to begin with min_fault_length) but on the long term control various other map_checker and Ranee map simplification codes

**Comment by yohanderose** [comment]
Hey @markjessell, this feature was finished in b1b296229c2ada89161f638037af5d4e45eb3fa6 and is available with a master pull. I have moved the definition of run flags to the update_config function in project.py. You can access this **dictionary of flags** using self.run_flags within project and config.

**Note to everyone previously passing flags to the run function:**  you now need to pass them to config as so
```python
proj.update_config(
    out_dir='sa-remote',
    overwrite='true',
    ...
    quiet='no-figures',
    run_flags={'fold_decimate': 5}
)
```

This is the default run flag dictionary.
```python
            self.run_flags = {
                'aus': True,
                'deposits': "Fe,Cu,Au,NONE",
                'dtb': '',
                'orientation_decimate': 0,
                'contact_decimate': 5,
                'intrusion_mode': 0,
                'interpolation_spacing': 500,
                'misorientation': 30,
                'interpolation_scheme': 'scipy_rbf',
                'fault_decimate': 5,
                'min_fault_length': 5000,
                'fault_dip': 90,
                'pluton_dip': 45,
                'pluton_form': 'domes',
                'dist_buffer': 10,
                'contact_dip': -999,
                'contact_orientation_decimate': 5,
                'null_scheme': 'null',
                'thickness_buffer': 5000,
                'max_thickness_allowed': 10000,
                'fold_decimate': 5,
                'fat_step': 750,
                'close_dip': -999,
                'use_interpolations': True,
                'use_fat': True
            }
```

Passing in any of the above keys will update the internal dictionary - without resetting anything if you already have self.run_flags instantiated. Ie. if you had already set up config and run it, with 
```python 
run_flags={'aus'=False, 'fold_decimate'=10} 
````
and wanted another run with a fold decimate of 5, you could either go
```python
proj.run_flags['fold_decimate'] = 5
proj.run()
```
or if you wanted a different output directory etc 
```python
proj.update_config(
    out_dir='/usr/bin/lol',
    overwrite='true',
    ...
    run_flags={'fold_decimate': 5}
)
```
Crucially, the aus=False flag doesn't reset to the default, which is helpful if you want to keep old settings and not remember every single one.
