### ISSUE TITLE
local variable 'project_crs' referenced before assignment

### ISSUE THREAD

**Issue by Kodibarba** [Loop3D/map2loop-2#87]
I tried to run the proj.run() function using my own data and then got this error 

> local variable 'project_crs' referenced before assignment

I saw that I could use **working_projection** instead, but I got the same error for project_crs. 

the details of the error are below: 

`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Input In [2], in <cell line: 14>()
      2 from map2loop.project import Project
      4 proj = Project(
      5                   geology_file='C:/Users/rcha0044/LoopPhD/ArcGIS files/Flinders Ranges/Shapefiles/Odla_wirra_area_east_by_minage_GDA94_2.shp',
      6                   fault_file='',
   (...)
     11                   metadata='./oodla_wirra_east_config.hjson'
     12                 )
---> 14 proj.update_config(
     15                     out_dir='oodla_wirra_east',
     16                     overwrite='true',
     17                     bbox_3d={
     18                         'minx': 3.27330661e+05 ,
     19                         'miny': 6.32155212e+06 ,
     20                         'maxx': 3.38277181e+05 ,
     21                         'maxy': 6.36982397e+06 ,
     22                         'base': 0,
     23                         'top':  1},
     24                     run_flags={'local' : True,
     25                         'aus': True,
     26                         'close_dip': -999,
     27                         'contact_decimate': 5,
     28                         'contact_dip': -999,
     29                         'contact_orientation_decimate': 5,
     30                         'deposits': "NONE",
     31                         'dist_buffer': 10,
     32                         'dtb': '',
     33                         'fat_step': 750,
     34                         'fault_decimate': 5,
     35                         'fault_dip': 90,
     36                         'fold_decimate': 5,
     37                         'interpolation_scheme': 'scipy_rbf',
     38                         'interpolation_spacing': 500,
     39                         'intrusion_mode': 0,
     40                         'max_thickness_allowed': 10000,
     41                         'min_fault_length': 5000,
     42                         'misorientation': 30,
     43                         'null_scheme': 'null',
     44                         'orientation_decimate': 0,
     45                         'pluton_dip': 45,
     46                         'pluton_form': 'domes',
     47                         'thickness_buffer': 5000,
     48                         'use_fat': False,
     49                         'use_interpolations': False,
     50                         'fault_orientation_clusters':False,
     51                         'fault_length_clusters':False,
     52                         'use_roi_clip':False,
     53                         'roi_clip_path':'',
     54                          },
     55                     proj_crs={'init': 'epsg:28354'},
     56                     clut_path= '',
     57                     quiet='None'
     58                   )
     60 proj.run()

File C:\Anaconda3\envs\map2loop3\lib\site-packages\map2loop-1.2.8-py3.9.egg\map2loop\m2l_utils.py:1482, in timer_decorator.<locals>.clean(*args, **kwargs)
   1481 def clean(*args, **kwargs):
-> 1482     return func(*args, **kwargs)

File <@beartype(map2loop.project.Project.update_config) at 0x2b74b183040>:47, in update_config(__beartype_func, __beartype_raise_exception, *args, **kwargs)

File C:\Anaconda3\envs\map2loop3\lib\site-packages\map2loop-1.2.8-py3.9.egg\map2loop\project.py:380, in Project.update_config(self, overwrite, bbox_3d, dtm_crs, step_out, clut_path, model_engine, run_flags, **kwargs)
    377     bbox_3d = {'minx':0,'maxx':1000,',miny':0,'maxy':1000,'base':-10000,'top':1200}
    379 if self.map_data.working_projection == None:
--> 380     if project_crs in kwargs:
    381         warnings.warn("project_crs in update_config is deprecated and will be removed in later versions of map2loop.  Please use the working_projection parameter in Project instead", DeprecationWarning)
    382         project_crs = kwargs['proj_crs']

UnboundLocalError: local variable 'project_crs' referenced before assignment`

**Comment by RoyThomsonMonash** [comment]
This error was fixed in the 1.3.0 release. It was lingering code for the deprecation of using project_crs in the update_config function.  Using the working_projection parameter in Project initialisation is the preferred method.
