### ISSUE TITLE
[BUG] exported shapefiles don't have filenames and structures are polylines

### ISSUE THREAD

**Issue by markjessell** [Loop3D/map2loop-2#99]
### Describe your issue

proj.save_mapdata_to_shapefiles(proj.config.project_path)

produces a series of directories(e.g. GEOLOGY/.shp) which contain a shapefile called ".shp.shp"

In addition the STRUCTURES shapefile is a polyline, but should be oints, and is empty

### Minimal reproducing code example

```python
proj.run()
proj.save_mapdata_to_shapefiles(proj.config.project_path)
```

### Error message

```shell
n/a
```

**Comment by RoyThomsonMonash** [comment]
Bug fixed in release 1.3.6
